name: BuildAndTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We need the JDK 11 to build the project because of Javadoc
        java: [ '11', '17' ]
    name: Java ${{ matrix.Java }} BuildAndTest

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Test
      run: ./gradlew check