name: Javadoc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # For the javadoc tasks specifically we use Java 11 instead of Java 8
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.Java }} Javadoc

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Javadoc generation
      run: ./gradlew javadoc